### PR TITLE
Store `user_mac_key` in keychain (Mac OS X only)

### PR DESCRIPTION
**Pull request by ePirat**
Store `user_mac_key` in keychain (Mac OS X only) and not plain text which could be a small security risk, if another app uses it to send posts, etc…

### CODE REVIEW

**Comment by jeena** [comment]
Very nice, one problem though, it stores the key in the keychain but doesn't use it there from while authentication later on while posting or getting data: https://github.com/ePirat/Tentia/blob/master/WebKit/scripts/helper/Paths.js#L43 if you  remove the file ~/Library/Preferences/nu.jabs.apps.tentia.plist and start using Tentia like a new user then you will see that it is impossible to authenticate to the server.

And one more thing, if the app already is authorized then it doesn't move the key into the keychain, but that is something I can implement easily.

**Comment by ePirat** [comment]
Ok, forgot one file ;) 
And it will move the key, see here: https://github.com/ePirat/Tentia/commit/c4fdb2b5cd9b0c30496ad1060d91fba505b2c02f#L2R66

(It even removes the key from the plist afterwards to not continue to have the data exposed as plaintext)

**Comment by jeena** [comment]
Ah of course you're right :D I will download, build and test your changes and if everything works we will have a 0.3.1 to publish :D

**Comment by ePirat** [comment]
Ok. There is still some error handling to do, for the very rare case the user does not allows the app to access the keychain… But have to read bit more about it in the docs…

**Comment by jeena** [comment]
Yes, but it is something for some other version, there are many edge cases like this, stuff like what happens if the user only allows some but not all post types and stuff.

**Comment by poweruser82** [comment]
In my keychain I have an entry for Tentia. It has "TentiaUserAccount" in the account field. Wouldn't be better if it were the real entity URL? So you can store a key for each account.

**Comment by jeena** [comment]
Yeah true, but for now irrelevant since right now tentia only allows one account, not sure when and if will support multiple accounts, it should but this would need quite many design changes.

**Comment by poweruser82** [comment]
It can be useful now. If not just to change the entity in the preferences for testing purposes without having to authorize the client each time.

**Comment by jeena** [comment]
Hm true, it is a good idea actually, it could be the poor mans multiple account thingy for now, you could either "Log out" or "Change entity", good idea, could you open a new ticket for that?

**Comment by ePirat** [comment]
Yes right, I have to admit I was to lazy to care about where getting the username from, cause it would have needed some a bit more complex changes… Maybe I will have tonight some time to fix it…

**Pull request merged**
