### PR TITLE
added “follows since <timeago>”

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jeena** [comment]
Very cool, even if there are 2 problems yet with the follows since &lt;timeago> thingy.

First it doesn't show up because you are adding a &lt;p> into within a &lt;p>, it should be first a &lt;br> and then a textnode instead.

Second, for both Following and Followed by it says "follows since ..." which could be misleading, I'm not sure how to distinguish it yet, perhaps "Started to follow: 5 days ago" and "Followed: 5 days ago"?

**Comment by ghost** [comment]
why i can see it? http://i5.minus.com/im4GzdiFhvBUY.jpg

i can't say by first look if list consist of followers or followings either, only if i see my own avatar in it i know it's a followers list

**Comment by jeena** [comment]
Yes that is true too, I hoped we could make it clear with the text you added, that would be cool.

The fact that something works on your computer doesn't mean that it is the right thing to do ;-) You can sse here: http://www.whatwg.org/specs/web-apps/current-work/multipage/grouping-content.html#the-p-element that the &lt;p> only can contain parsing content, which is defined here: http://www.whatwg.org/specs/web-apps/current-work/multipage/elements.html#phrasing-content so no &lt;p> allowed within &lt;p>.

**Comment by jeena** [comment]
Btw. it wasn't there when I compiled this branch, if you trigger this error, then the behaviour of the rendering engine is undefined.

**Comment by jeena** [comment]
Very nice, thank you, I will merge it now and change the text later on if we find something better :)

**Comment by ghost** [comment]
k

**Pull request merged**
