### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by Nygu**
Known bugs:
- Date of first item is not displayed properly;
- Need to get rid of text-shadow on x-repost-dropdowns.

Motivation for changes:
- odd/even backgrounds on posts looked like dropshadows - flat colours look cleaner;
- white text-shadows on links make them stand out slightly better;
- unlabelling mentions make for easier reading and looks cleaner - normally these are used to display mentions in writing areas (publishers);
- right-border on hover is less intrusive than background-color changing;
- date-tab can be fiddly and get in your way by overlapping other posts - first post was inconsistent;
- font looks slightly better.

Changes that should go with this commit:
- Shorter TimeAgo (7s, 30m, 3h, 4d, 19 jan);
- Time should always be visible;
- Removing the "from SourceApp" from the date pane;
- Putting a picture of a more vertically aligned ^ or a @ in front of names. Personally I am really a sucker for the @ as people are so familiar with it.

Additional changes (requiring more work):
- Show SourceApp below the post upon clicking the post;
- Show "view conversation" link there as well;
- Eventually have a map there for posts with locations.

Last but not least, I rest my case: Green is more awesome! But I have been so kind to leave all the blue in. ;-)

### CODE REVIEW

**Comment by jeena** [comment]
Thank you very much for this pull request. Many of the changes are great and I will add them to the core but especially the one with removing the date tab and showing the timestamp permanently is troubling me.

I agree that clicking on the timestamp in the tab can be fiddely but I don't thing it is "in your way" by overlapping other posts, if you hover over this post then you most probably are reating it.

I'm not happy with the link to the conversation view being up there because there is never a indication if there is a conversation at all. I think we should try something else. What about adding it behind the name in this form:

`Kevin Kleinman in reply to Jeena`

Where `reply to Jeena` would be the link to the conversation view? Then you wouldn't need to fiddle with the timestamp. Hm but this doesn't work if you want to see if a post has "children", so not quite a clean solution :-/

The thing is that I just really don't like to stuff any more information into there where the whitespace is now which looks so clean right now. I didn't like it in the official OS X Twitter client and I don't like it here either because for me it is second class information and should be shown on demand.

I don't think putting a "^" or "@" is necessary either, you can distinguish if it is a profile or just a normal link quite easy because a normal Link always starts with http:// and even tags start with a # so you won't ever be confused about the linked names.

Moving the links from the date tab to the bottom of the post and showing them on click of the post seems very odd because 1. nobody will ever click on the post, it is nothing you'd expect and 2. if they click and we show it then all the content after this post would have to be moved down to make some place for the link (I don't like content jumping up and down), or the post would need to have this like with whitespace which would lead to less posts visible on the screen at the same time. Back then I decided to use the tab especially to solve this problems.

**Comment by Nygu** [comment]
Hi Jeena, thanks for the reply. I'll get back to you tomorrow. ;-)

**Comment by jeena** [comment]
Ah now, after removing the background from the names I remember why I put the background there and understand your desire for some character before them :-/ it is because otherwise you can't know if `Tobias Tom how are you.` you got two users `Tobias` and `Tom` or just one user `Tobias Tom`. Would people add a seperator like a `,` or something like in normal language then there would be not a problem, and they seem to do that on Facebook, but nobody seems to do that on Tent, but it is perhaps just because the defaults when answering on a post don't put a `,` in between.

I think putting a `@` or `^` before is a really lazy workaround and I hope we can find something better, perhaps just automatically putting a `,` in between them if there is no other word in between or something?

**Comment by Nygu** [comment]
I automatically add a comma behind every name in my own fork but if you can automatically check if there's something in between names, then that would be a nice solution. Regarding the sign before the name; that's just what people are used to and it may help them to understand how to create mentions. I mostly try to go with the Twitter paradigm because everyone understands that.

Anyway, on to your first post:

I believe we should distinguish primary information and secundairy information. Primary, to me, are:
- Avatar;
- Name;
- Post;
- Date.

Those are the things you need to determine what the message is, who sent it and when they sent it. When I see posts in my stream, I immediately want to know whether they are new or old, without having to hover it first. Having the date visible at all times helps me in doing so. Having a shorter date improves the ease of checking for new posts and it looks cleaner in the app. If you have a look around, you will notice that almost any microblog app does this so people are familiar with that.

When you hover over the post, you can access the user controls you need to respond to it, whether it be a reply, repost or even a bookmark. Nothing wrong with that.

I consider the app source of the message secundairy. Most people really don't care where the message comes from so it's not essential to show that information. I suggested hiding it until after clicking because in that case it would still be accessible and the info would still be tied to the post, for those who want to access it. Regarding content jumping up and down: that only happens when you click it.

I literally just found out about the conversation view. I thought it wasn't implemented in Linux because I never considered clicking the timestamp. So that's not really a clean solution. I never suggested to show the conversation link in the date tab. From what you wrote I believe that's what you think. I thought if we'd hide the app source in a hidden pane below the post, then we might as well put a "view conversation" in that hidden section as well, as another piece of secundairy information. The general behavior would be: if you would like to know more about a certain post (aka children/parents), click it. I'm pretty sure that's what people are going to try because that is how Twitter but also Tentr works.

However, perhaps it would be a good idea to add some sort of icon to the hover interface which indicates a conversation, whether it consists of children or parents. That would be a new, more obvious direct link to the conversation view, though it can easily be confused with the action icons.

Anyway, when I don't hover a post I really miss the date and when I do hover a post I really don't need to see the source. That source was fun back when it was introduced but I'm sure most people don't pay a whole lot of attention to it anymore.

Some food for thought. ;-)

**Comment by Nygu** [comment]
Here's one way to structure posts: http://i.imgur.com/R0gbBUP.png.

The little extra space it takes adds to the look of the app and you can have all the same information you have now without it overlapping with the reshares. It also leaves room for an eventual like or bookmark icon. Though personally I stick with my opinion that adding click-post functionality would be more awesome. That's just more compact, more complete and more familiar.

**Comment by jeena** [comment]
Hm yeah, but don't you think that they look heavy at the top and too light at the bottom when do are not hovering above them (which is like 99,99% of the time)?

**Comment by jeena** [comment]
What about if we add the time after the time so it would say "_Jeena_ 4 min ago"?

And I actually like the look of the tab and I think we could leave the info about the app there. As far as I understand it it is mostly the time people want to see al the time (not only on hover) and they find it sometimes difficult to click on the time up there in the tab because it is so near the other post and it disappears when you move your mouse a bit. But as you said most people don't click on the app name.

**Comment by poweruser82** [comment]
I'd like `Xxx [in reply to Yyy] zzz ago` with in reply to as an anchor to the Yyy post in timeline. The conversation view would be evoked with another button like repost, reply, delete.

**Comment by jeena** [comment]
It can get quite long:

`Jonathan Rudenberg in reply to Jeremy / Sleepy Daddy Software™ 5 hours ago [reposted] by Jeremy / Sleepy Daddy Software™`

**Comment by poweruser82** [comment]
Repost could go in an optional separate line at the bottom of the post saying `Reposted by /(you and )?((:the_only_one_reposter_name)|(:the_number_of_reposter people))/`

**Comment by jeena** [comment]
That is a good idea actually.

**Comment by Nygu** [comment]
Regarding the time: I believe the shorter the date, the more functional. By always showing it in the top-right corner, viewing the time will always be a consistent experience. You can simply scan through the top-right corners of the stream to see the time spread between posts.

**Comment by jeena** [comment]
Hm yeah short top right would be the best, but perhaps we can add the buttons on hover left of the time/date thing? That would even fix the OS X problem where you can't click because of the freaking scrollbar!

**Comment by jeena** [comment]
I have implemented now the things I liked from this pull request which were:
- moved time ago so it is visible all the time
- shortened time ago to 1m, 5d, etc.
- removed the odd/even background dropshaddows
- unlabeling names
- second font is "Open Sans" and "Ubuntu"
- I didn't put a @ or ^ before the name, instead if there is more then one name after each other I put a ", " in between
- show conversation got its own icon when you hover
- there is a map now for posts with locations (the look of it will be a subject of change in the future)

I will open a new issue for the "reposted by" problem.

**Comment by jeena** [comment]
https://github.com/jeena/Bungloo/issues/163 is the new issue

**Pull request closed without merging**
